### ISSUE TITLE
Crash in ScanUtils

### ISSUE THREAD

**Issue by hannesa2** [hannesa2/LiveEdgeDetection#10]
https://github.com/hannesa2/LiveEdgeDetection/blob/555febc7f4784df40bab40f71a2869303f913cd8/liveedgedetection/src/main/java/com/adityaarora/liveedgedetection/util/ScanUtils.java#L359

This line causes 
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/3314607/69517116-10198980-0f54-11ea-859e-645a59246b36.png">

**Comment by zakblacki** [comment]
[Read I mentionned everything](https://github.com/adityaarora1/LiveEdgeDetection/issues/39#issuecomment-583693747)

**Comment by hannesa2** [comment]
@zakblacki 
Thank you for the info.
I currently switched to `openCV 4.3.0` https://github.com/hannesa2/LiveEdgeDetection/pull/49
