### ISSUE TITLE
Language update

### ISSUE THREAD

**Issue by klaszlo8207** [hannesa2/LiveEdgeDetection#101]
Can I update somehow the strings in my language?

"Move closer" and that strings

Thanks

**Comment by hannesa2** [comment]
Simply overwrite it with a same string name and an own content

<img width="369" alt="image" src="https://user-images.githubusercontent.com/3314607/99520702-b8a9d000-2993-11eb-97a6-4bbb9751af67.png">

**Comment by klaszlo8207** [comment]
Sorry but I can't because that string is on the library itself :D

**Comment by hannesa2** [comment]
That's not a problem. Try it
