### ISSUE TITLE
Image size seems to be limited by dimensions of phone's display

### ISSUE THREAD

**Issue by niekvse** [hannesa2/LiveEdgeDetection#112]
The resulting bitmap image dimensions after performing a scan and capturing the image seems to be limited to something that is smaller than the dimensions of the phone's display. This seems somewhat limiting when a user may want to zoom into what was scanned, or use a higher resolution version for further processing. Also, it means that the resulting image size depends on how the image was scanned: close to the camera or further away from it.

It seems to be partly a result of the following code in `ScanActivity`:

```kotlin
override fun onPictureClicked(bitmap: Bitmap) {
        try {
            copyBitmap = bitmap.copy(Bitmap.Config.ARGB_8888, true)
            val height = window.findViewById<View>(Window.ID_ANDROID_CONTENT).height
            val width = window.findViewById<View>(Window.ID_ANDROID_CONTENT).width
            copyBitmap = copyBitmap?.resizeToScreenContentSize(width, height)
```

Is this functionality planned to be changed some time in the future? Possibly the main calculations can still be done on lower resolution images, but then the final (scaled) transformation should be done on a full res (or at least higher resolution) image.

**Comment by alexkulakovsky** [comment]
+1

**Comment by hannesa2** [comment]
It makes sense. As I don't see a pull request, I guess I've the honor ...

**Comment by hannesa2** [comment]
Please give it a try https://github.com/hannesa2/LiveEdgeDetection/releases/tag/1.7.0
