### ISSUE TITLE
openCV is not reachable anymore

### ISSUE THREAD

**Issue by reshadf** [hannesa2/LiveEdgeDetection#221]
hi since a few days we get the following from our CI and when trying to reach it manually:

https://artifactory.mxtracks.info is not available. is this a known issue? 

```
* What went wrong:
27
Could not determine the dependencies of task ':app:compileDevelopDebugKotlin'.
28
> Could not resolve all files for configuration ':app:productionDebugRuntimeClasspath'.
29
   > Could not resolve OpenCV_all_together_samples:opencv:4.5.2.0.
30
     Required by:
31
         project :app > com.github.hannesa2:LiveEdgeDetection:1.8.10
32
      > Could not resolve OpenCV_all_together_samples:opencv:4.5.2.0.
33
         > Could not get resource 'https://artifactory.mxtracks.info/artifactory/gradle-dev-local/OpenCV_all_together_samples/opencv/4.5.2.0/opencv-4.5.2.0.pom'.
34
            > Could not GET 'https://artifactory.mxtracks.info/artifactory/gradle-dev-local/OpenCV_all_together_samples/opencv/4.5.2.0/opencv-4.5.2.0.pom'.
35

36
               > Connect to artifactory.mxtracks.info:443 [artifactory.mxtracks.info/89.247.201.131, artifactory.mxtracks.info/2001:16b8:2700:445a:3631:c4ff:fe40:6a8e] failed: Network is unreachable (connect failed)
```

**Comment by reshadf** [comment]
ok thanks! is it an idea to host this on the central maven repo for future uptime guarantees? or is it possible to host it ourselves?

**Comment by hannesa2** [comment]
When it's online again you are very welcome to make a pull request to publish to maven central.
Of course you can host it by yourself as well.

Background: I was forced to host it on my side, because the repo was to big for a free github repo. If you have a payed account you can transfer it of course to your side as well

**Comment by hannesa2** [comment]
It's working again

**Comment by markvanderlaan** [comment]
Hi, since a few days we get this error again from our CI. Is this a known issue?

**Comment by filipef101** [comment]
@hannesa2 getting this, server down?
