### ISSUE TITLE
ScanUtils does not have decodeBitmapFromFile method

### ISSUE THREAD

**Issue by Aadil123** [hannesa2/LiveEdgeDetection#302]
There is no method called decodeBitmapFromFile in ScanUtils. The method is available in FileUtilsKt.

Please modify README to change
Bitmap baseBitmap = ScanUtils.decodeBitmapFromFile(filePath, ScanConstants.IMAGE_NAME);

to

Bitmap baseBitMap = FileUtilsKt.decodeBitmapFromFile(filePath);

**Comment by hannesa2** [comment]
Thanks for the hint. I switched to Kotlin style
