### ISSUE TITLE
Does not crop properly to dimensions set

### ISSUE THREAD

**Issue by truongvimit** [hannesa2/LiveEdgeDetection#343]
I still have this problem on version 1.8.19.
Live Edge Detection is true but crop incorrect size

**Comment by mohammedkhader** [comment]
@hannesa2  any suggestion?

**Comment by hannesa2** [comment]
Can you show me your example ?

**Comment by mohammedkhader** [comment]
![image](https://user-images.githubusercontent.com/8732385/205089681-2fec623b-239a-45bd-8b2f-6aad40b6ea27.png)

and the result is 

![image](https://user-images.githubusercontent.com/8732385/205089872-b988c591-e333-476f-b890-bdfefb3287d9.png)
