### ISSUE TITLE
Reduce Camera Preview Callbacks & Live Detection to Cropping

### ISSUE THREAD

**Issue by mohit67890** [hannesa2/LiveEdgeDetection#62]
Hi, Thanks for making this repo. 
Actually, I wanted to know if I could just lower down the preview callbacks, so that once an object is detected the points stays for a second and also when we click the photo, can the same photo with the rectangular points be used instead of again running the draw rect. 
I tried to do it but data to Bitmap gives me an error that it cannot be null . 
I don' t know where I'm going wrong in this. 

Regards,
Mohit

**Comment by hannesa2** [comment]
I guess everything could be done, but when I don't see what you did, it's hard to help

**Comment by mohit67890** [comment]
Hi, If you go to the LiveDetection Module, in that ScanSurfaceView -> PreviewCallback, in this function if you try to convert the ByteArray (data) to Bitmap using FileUtils, it will give you an error.

**Comment by hannesa2** [comment]
Neither you gave me an example, nor the exact error message. 👎 
This is not the way, how it works !

You can give this a try

                val previewSize = camera.parameters.previewSize
                val yuvimage = YuvImage(data, ImageFormat.NV21, previewSize.width, previewSize.height, null)
                val baos = ByteArrayOutputStream()
                yuvimage.compressToJpeg(Rect(0, 0, previewSize.width, previewSize.height), 80, baos)
                val jdata: ByteArray = baos.toByteArray()
                val bitmap = BitmapFactory.decodeByteArray(jdata, 0, jdata.size)
                Timber.d("BITMAP ==> $bitmap")

When you know a working solution, please post it here

**Comment by mohit67890** [comment]
Hey Sorry for the that, I can understand that by not providing the decode its difficult. 
The above code worked. But somehow I felt that the image quality hasn't been good. 
Also, in the original liveedgedetection, the output quality is not optimum. is it due to jpg compression or something else ?

Also, can you try a bit in relation to focusing the edge points, because the edge points flicker a lot sometimes.

**Comment by hannesa2** [comment]
My idea is to detect blur with openCV till it has an acceptable value. But currently only as an Idea

**Comment by hannesa2** [comment]
Concerning the image quality: Please give it a try https://github.com/hannesa2/LiveEdgeDetection/releases/tag/1.7.0
