### ISSUE TITLE
Failed to resolve: opencv_samples:opencv:4.3.0

### ISSUE THREAD

**Issue by mishraaditya595** [hannesa2/LiveEdgeDetection#67]
When I try to sync the Gradle after including the dependency, I get this error. What should I do?

**Comment by hannesa2** [comment]
The maven server is sometimes temporary offline. Does it still exists ?

Please try it again with `./gradlew clean --refresh-dependencies`

<img width="632" alt="image" src="https://user-images.githubusercontent.com/3314607/89303727-dc5b3b80-d66c-11ea-9d66-7b335f33a865.png">

**Comment by mishraaditya595** [comment]
Yeah,
![Capture](https://user-images.githubusercontent.com/54946784/89304552-310daf00-d68b-11ea-94ac-1898d817a7ea.PNG)
 it still exists.

**Comment by hannesa2** [comment]
Hmm, it's there https://artifactory.mxtracks.info//artifactory/gradle-dev-local/opencv_samples/opencv/4.3.0/
and it works here with `./gradlew clean --refresh-dependencies`

You are not on latest master, it has `4.4.0`

**Comment by hannesa2** [comment]
I tested it on an other machine as well, and it is **working properly**.
CI builds as well.

To be honest, it looks like it's located on your machine.

I'll close it, and if it still exists, please reopen it

**Comment by bperel** [comment]
I have this issue as well, even after running `./gradlew clean --refresh-dependencies`.
The only changes that I did to try to use the library is to add the jitpack repo and the dependency in build.gradle.

Is there anything that I can do to try and fix the issue? I've tried "Clean project" and "Rebuild project", without luck.

**Comment by hannesa2** [comment]
I tested in an other machine again. Tell me, what's the difference to you ?

![image](https://user-images.githubusercontent.com/3314607/89330839-1e967400-d691-11ea-81ec-da5f0f9d01e4.png)

**Comment by bperel** [comment]
Here it is. Seems to be an issue on Jitpack's side?
```
$ ./gradlew clean build --info
...

> Configure project :
...

> Configure project :app
Evaluating project ':app' using build file '/myproject/app/build.gradle'.
Creating configuration androidTestUtil
Configuring Java sources compilation with source level 1.8 and target level 1.8.
Configuring Java sources compilation with source level 1.8 and target level 1.8.
Configuring Java sources compilation with source level 1.8 and target level 1.8.
Configuring Java sources compilation with source level 1.8 and target level 1.8.
Configuring Java sources compilation with source level 1.8 and target level 1.8.
All projects evaluated.
Selected primary task 'clean' from project :
Selected primary task 'build' from project :
Resource missing. [HTTP HEAD: https://repo.jfrog.org/artifactory/libs-release-bintray/opencv_samples/opencv/4.3.0/opencv-4.3.0.pom?referrer]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/opencv_samples/opencv/4.3.0/opencv-4.3.0.pom]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/opencv_samples/opencv/4.3.0/opencv-4.3.0.pom]
Resource missing. [HTTP HEAD: https://jitpack.io/opencv_samples/opencv/4.3.0/opencv-4.3.0.pom]
Registered task dependencies: app:debugCompileClasspath
Starting dependency analysis

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not find opencv_samples:opencv:4.3.0.
     Required by:
         project :app > com.github.hannesa2:LiveEdgeDetection:1.3.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

```

**Comment by hannesa2** [comment]
Because you are not on current master, please tell me on which commit you are. 

You do it with `git rev-parse HEAD`

**Comment by bperel** [comment]
I'm not on any commit, I integrate your library in my build.gradle using : 
`implementation 'com.github.hannesa2:LiveEdgeDetection:1.3.2'`

**Comment by hannesa2** [comment]
I use it here
https://github.com/hannesa2/owncloud-android/pull/5/files#r465506411
and CI builds properly
https://github.com/hannesa2/owncloud-android/pull/5/checks?check_run_id=948067842

This is the evidence that it's working on CI (and on my machine)

**Comment by hannesa2** [comment]
@bperel 
To continue here, please show me a non-working (demo-)repo

**Comment by bperel** [comment]
Sorry, I don't have enough knowledge about Android CI to do that. But is it expected that Gradle can't find `opencv-4.3.0.pom` in any of the repositories? Excerpt from the log in a previous comment:
```
Resource missing. [HTTP HEAD: https://repo.jfrog.org/artifactory/libs-release-bintray/opencv_samples/opencv/4.3.0/opencv-4.3.0.pom?referrer]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/opencv_samples/opencv/4.3.0/opencv-4.3.0.pom]
Resource missing. [HTTP HEAD: https://dl.google.com/dl/android/maven2/opencv_samples/opencv/4.3.0/opencv-4.3.0.pom]
Resource missing. [HTTP HEAD: https://jitpack.io/opencv_samples/opencv/4.3.0/opencv-4.3.0.pom]
```

**Comment by hannesa2** [comment]
Yes. And CI can do it (me too)

Share your repo and we will see

**Comment by hannesa2** [comment]
> Sorry, I don't have enough knowledge about Android CI to do that.

The CI does the same like you did. With the diff if being successful

**Comment by carlosgasa** [comment]
> The maven server is sometimes temporary offline. Does it still exists ?
> 
> Please try it again with `./gradlew clean --refresh-dependencies`
> 
> <img alt="image" width="632" src="https://user-images.githubusercontent.com/3314607/89303727-dc5b3b80-d66c-11ea-9d66-7b335f33a865.png">

It works for me, I did it here 
![image](https://user-images.githubusercontent.com/25380778/96201923-753aec80-0f23-11eb-877c-69b9eb4f9c32.png)

**Comment by maboueita** [comment]
Encountering the same issue as well. Building the project gives 
`Could not find opencv_samples:opencv:4.4.0`

**Comment by hannesa2** [comment]
For CI and me it works, but can build this library by yourself too 
https://github.com/hannesa2/LiveEdgeDetection/blob/master/liveedgedetection/build.gradle#L27-L30

**Comment by hannesa2** [comment]
Or you can download artifact here https://git.mxtracks.info/opencv/openCV-android-sdk/-/jobs/3697

But I see, it was removed automatically from job (maybe I should change this)
<img width="345" alt="image" src="https://user-images.githubusercontent.com/3314607/98273695-d12cea00-1f92-11eb-99fa-0e79b0f6d145.png">
This is normally not a big issue, because it's downloaded from artifactory, you can download aar direcly from here https://artifactory.mxtracks.info//artifactory/webapp/#/artifacts/browse/tree/General/gradle-dev/opencv_samples/opencv/4.4.0/opencv-4.4.0.aar

**Comment by bperel** [comment]
@hannesa2 Could you perhaps explain how to set up the dependencies (both LiveEdgeDetection and OpenCV) using the AAR in the README file?
I tried to include LiveEdgeDetection in my project on a new machine and got the exact same error as before.
After downloading the AAR from the link in your comment I tried to include it in my app `build.gradle` like this by adding`*.aar` in the list of included file patterns : 
```
    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')
    implementation 'com.github.hannesa2:LiveEdgeDetection:1.4.0'
    api 'com.github.MikeOrtiz:TouchImageView:3.0.3'
```

it looks like the AAR file does not correspond to a dependency that LiveEdgeDetection can use : `Failed to resolve: opencv_samples:opencv:4.4.0`

**Comment by hannesa2** [comment]
The openCV repo comes with a size of 25 GB and it's public access able.
I tested it with a monthly paid fee to extend gitls extension, but build with jitpack.io fails too.
So I gave up, to spend my time with errors in third party services. Now I build and host by my own.

In the code there is somewhere a comment about this. 
To be honest I never seen this errors on my side and CI build properly too

**Comment by hannesa2** [comment]
Btw, anyone in warmly welcome helping to make openCV build on jitpack.io

**Comment by hannesa2** [comment]
I guess this is the solution

` maven { url 'https://artifactory.mxtracks.info/artifactory/gradle-dev-local/' }`

Please give it a try

**Comment by bperel** [comment]
It does fix it, thnk you @hannesa2 !
