### ISSUE TITLE
Document detection rectangle has an vertical offset on Android 5 and 6

### ISSUE THREAD

**Issue by cgisca** [hannesa2/LiveEdgeDetection#69]
Hello @hannesa2 ,
I was encountering next issue on devices Huawei P8 (Android  6) and on Samsung J3 (Android 5). Note that on other phones with android version greater then 7, this issue does not persist, thus it is working just fine.

As it is seen in first image below, the drawn rectangle on the detected document has a small offset on vertical axis. However in the captured image preview the rectangle is calculated correctly. Do you have any ideas why is it happening on certain devices? Thank you!

![Image1](https://user-images.githubusercontent.com/4255200/89728975-11370c00-da3a-11ea-9964-6f6ba24153ee.jpeg)
![Image2](https://user-images.githubusercontent.com/4255200/89728976-1300cf80-da3a-11ea-8434-eb70770311a4.jpeg)

**Comment by hannesa2** [comment]
Sorry, I've no Huawei P8 to verify.
You could use Android Layout inspector 
![image](https://user-images.githubusercontent.com/3314607/89729253-0b3e2c80-da34-11ea-81d7-1cf1731d02a8.png)

to investigate if Huawei P8 has some hidden (?) layouts, which cause this offset.
Or at least compare generated layout with a working device generated layout, then you know what's the diff is

**Comment by hannesa2** [comment]
When there is no diff in Layout Inspector, then the source is in `onDraw()`
