### ISSUE TITLE
Clicking Multiple Pics in a single session

### ISSUE THREAD

**Issue by UtkarshBhatthere** [hannesa2/LiveEdgeDetection#71]
Hey I wished to take multiple pictures in a single session. But some event is taking place (maybe an internal callback or something) which is disrupting the resumption. Can you please point out what section of your code will need changes for continuous clicking ?

**Comment by UtkarshBhatthere** [comment]
For more info on this, I actually used the exact code from your demo scanActivity and it’s layout now I have already removed the arrangements from the activity which make it run for the result, but I am still unsure of what happens after the onClick handler for the accept button get executed that the whole activity takes a soft reset sort of thing. So how can I use your (pretty cool) library for multiple image sessions ?

**Comment by hannesa2** [comment]
When I understand right, this is probably the right place to handle it https://github.com/hannesa2/LiveEdgeDetection/pull/124/files

**Comment by UtkarshBhatthere** [comment]
Thanks for replying to the issue, you took some time so I wrote my own native code for the document detection, your code came in real handy while getting to know the physics behind this. Thanks!

**Comment by hannesa2** [comment]
Please can you share your code ?

**Comment by UtkarshBhatthere** [comment]
yeah sure I'll share my code with you.
