### ISSUE TITLE
ERROR: For input string: ""

### ISSUE THREAD

**Issue by KylieGabay** [hannesa2/LiveEdgeDetection#74]
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Kylie's\Downloads\LiveEdgeDetection-1.4.0\build.gradle' line: 59

* What went wrong:
A problem occurred evaluating project ':app'.
> For input string: ""
```

For some reason, it fails to build the gradle..

**Comment by hannesa2** [comment]
You are the first person I know, who uses the download auto-generated zip code from release 😄 
The code needs to be a git repo for generate version code.
It's more easy to simply clone repo

**Comment by KylieGabay** [comment]
OHHHHHHHH. I see. Thank you so much
I am only a beginner. Sorry 😂
