### ISSUE TITLE
Failed to resolve: opencv_samples:opencv:4.4.0

### ISSUE THREAD

**Issue by durgeshrjkumar** [hannesa2/LiveEdgeDetection#77]
it gives this error when implementing the latest version

**Comment by hannesa2** [comment]
Maybe like https://github.com/hannesa2/LiveEdgeDetection/issues/67#issuecomment-669012112

Ci builds properly.
Please share your project

**Comment by hannesa2** [comment]
Ci builds https://github.com/hannesa2/LiveEdgeDetection/pull/76/checks?check_run_id=990554928 just minutes ago

**Comment by durgeshrjkumar** [comment]
but why error in android studio?

**Comment by hannesa2** [comment]
Please share your project

**Comment by hannesa2** [comment]
I guess this is the solution

` maven { url 'https://artifactory.mxtracks.info/artifactory/gradle-dev-local/' }`

Please give it a try

**Comment by hannesa2** [comment]
This will fix it f4adff4
