### ISSUE TITLE
Cannot access 'androidx.lifecycle.HasDefaultViewModelProviderFactory'

### ISSUE THREAD

**Issue by KylieGabay** [hannesa2/LiveEdgeDetection#81]
> Cannot access 'androidx.lifecycle.HasDefaultViewModelProviderFactory' which is a supertype of 'info.hannes.liveedgedetection.activity.ScanActivity'. Check your module classpath for missing or conflicting dependencies

The code runs and all. But the ScanActivity is highlighted in red and I can't use it for my Android Applink.

I already tried adding this in the `build.gradle`
```
implementation "androidx.fragment:fragment:1.2.4"
implementation "androidx.activity:activity-ktx:1.1.0"
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
```
But it didn't work.
Thanks in advanced for the help

**Comment by hannesa2** [comment]
I was struggling with this too, this was my solution https://stackoverflow.com/a/62440430/1079990
