### ISSUE TITLE
 I have the following error Could not find opencv_samples:opencv:4.3.0.

### ISSUE THREAD

**Issue by MarcoGuapi** [hannesa2/LiveEdgeDetection#92]
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find opencv_samples:opencv:4.3.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/opencv_samples/opencv/4.3.0/opencv-4.3.0.pom
       - https://jcenter.bintray.com/opencv_samples/opencv/4.3.0/opencv-4.3.0.pom
       - https://jitpack.io/opencv_samples/opencv/4.3.0/opencv-4.3.0.pom
     Required by:
         project :app > com.github.hannesa2:LiveEdgeDetection:1.3.2

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by hannesa2** [comment]
Same to #77 and #67 

Btw, the latest master uses `4.4.0`

**Comment by hannesa2** [comment]
I guess this is the solution

` maven { url 'https://artifactory.mxtracks.info/artifactory/gradle-dev-local/' }`

Please give it a try
