### ISSUE TITLE
Failed to rebuild the project

### ISSUE THREAD

**Issue by MarcoGuapi** [hannesa2/LiveEdgeDetection#94]
Build file 'D:\Android\SeeCode\LiveEdgeDetection-master\LiveEdgeDetection-master\build.gradle' line: 56

A problem occurred evaluating project ':app'.
 For input string: ""
![image](https://user-images.githubusercontent.com/16675601/96956867-d2ecad00-14be-11eb-87d9-17c41c3fd090.png)

**Comment by hannesa2** [comment]
It looks like a local problem, here is my view 
<img width="762" alt="image" src="https://user-images.githubusercontent.com/3314607/96959836-339cd980-1501-11eb-844b-e416bc7b0c67.png">

Please try a `git clean -xdf` , close and open the project.
