### ISSUE TITLE
OutOfMemoryError 

### ISSUE THREAD

**Issue by klaszlo8207** [hannesa2/LiveEdgeDetection#98]
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.lang.OutOfMemoryError (no error message)

I just git clone ********* this lib, and then updated the NDK strings in the project. After that I want to run, but gave me this error...

**Comment by hannesa2** [comment]
But to investigate, you have to make a pull request.

Otherwise, I've to say: Sorry, CI works, so it's a local problem.

**Comment by hannesa2** [comment]
This repo 
* build any pull request on CI https://github.com/hannesa2/LiveEdgeDetection/actions
* run basic Espresso tests
* and make screenshots, which are uploaded

When you run into `OutOfMemoryError` only you are responsible
